### PR TITLE
DM-32UV: clear APRS fields in ChannelElement::encode()

### LINKED ISSUE #859: DM-32UV: ChannelElement::encode() doesn't clear APRS fields, breaks read-back
ChannelElement::encode() in dm32uv_codeplug.cc (lines 508-580) handles DMR channel properties (timeslot, color code, group list, radio ID, etc.) but never touches the APRS fields:
- enableDMRAPRS(bool) at byte 0x001c bit 2
- setDMRAPRSChannelIndex() at byte 0x0020 bits 0-3

When writing without --init-codeplug, the driver does a read-modify-write cycle. If the radio's factory codeplug had APRS enabled on some channels, those bits survive the encode. The result is a contradictory codeplug: the APRS settings block says "no system" (destinationId=0 from APRSSettingsElement::encode) but individual channels still have their APRS-enabled bits set pointing to index 0.

On read-back, link() at line 494 sees dmrAPRSEnabled()==true, tries to look up DMRAPRSSystem at index 0, finds none, and fails with "Unknown GPS system index 0."

For comparison, DMR6X2UVCodeplug::ChannelElement handles this correctly at dmr6x2uv_codeplug.cc line 1750.

Suggested fix in encode(), inside the DMR channel block around line 560:

```cpp
if (!dmr->aprsRef()->isNull() && dmr->aprsRef()->is<DMRAPRSSystem>()) {
  enableDMRAPRS(true);
  setDMRAPRSChannelIndex(ctx.index(dmr->aprsRef()->as<DMRAPRSSystem>()));
} else {
  enableDMRAPRS(false);
}
```

Also, link() at line 494 could be made tolerant like the DMR6X2UV version:

```cpp
if (dmrAPRSEnabled() && ctx.has<DMRAPRSSystem>(dmrAPRSChannelIndex())) {
```

This handles radios already written with the stale bits.

### PR DESCRIPTION
**Pull request by BeigeBox**
Fixes #859.

`ChannelElement::encode()` handles DMR channel properties (timeslot, color code, group list, etc.) but never touches the APRS enable bit (0x001c bit 2) or channel index (0x0020 bits 0-3).

During read-modify-write, factory APRS bits survive the encode. On read-back, `link()` sees `dmrAPRSEnabled()==true`, tries to look up a non-existent system at index 0, and fails with "Unknown GPS system index 0."

The fix:
1. Explicitly sets or clears APRS fields in `encode()` based on whether the channel has an APRS system configured
2. Makes `link()` tolerant of stale bits by adding a `ctx.has<>()` check, matching the pattern used by `DMR6X2UVCodeplug` at dmr6x2uv_codeplug.cc line ~1810

Builds and passes DM-32UV test on aarch64.

### CODE REVIEW

File: lib/dm32uv_codeplug.cc [hunk 1]
```diff
@@ -491,7 +491,7 @@ DM32UVCodeplug::ChannelElement::link(Channel *channel, Context &ctx, const Error
     else
       dmr->setRadioId(ctx.get<DMRRadioID>(dmrIdIndex()));
 
-    if (dmrAPRSEnabled()) {
+    if (dmrAPRSEnabled() && ctx.has<DMRAPRSSystem>(dmrAPRSChannelIndex())) {
```
Comment (hmatuschek) [inline lib/dm32uv_codeplug.cc]: This contradicts the line below. You can then remove the link-check. It will succeed.

**Comment by BeigeBox** [comment]
Good catch, removed the dead check.
